sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t jchen96/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jchen96/react-test npm run test

after_sucess:
    - docker build -t jchen96/movie-client ./client
    - docker build -t jchen96/movie-nginx ./nginx
    - docker build -t jchen96/movie-server ./server
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push jchen96/movie-client
    - docker push jchen96/movie-nginx
    - docker push jchen96/movie-server

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'movie-docker'
  env: 'MovieDocker-env-1'
  bucket_name: 'elasticbeanstalk-us-east-2-519589258831'
  bucket_path: 'movie-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  TMDbKey: "gjatOH44ZH8ePH5KZ1NBhBdHyl/1fNRxK4pl9RDveT31PFsdWAT4ojyTk69xG19kDMUgP/wY9GHOqSXw2x+p9XMsAeYQMvN285wRrIoDI7qskjjw8C2GTzW+KgKv36h1uazBOT6KEvI/n0uJkuaBrM4mP45MXodCag3HERx4wRrDy0fLljLo4ghyEUSgd6DOK0L69JdDiPLA6VvgHUYsj4vyisciiAPRvVtauIKe1I9IhLz0iXkRGDZPw6O5AwLOPs7VwvlS2L72Uk4G6t33c443Pe6XxWTSz5shK3mlhLuYGBsOFF++aN5nx2A5TQtJ+lDkU77GSD6oSqioLcwTyYMN750rHKGWtZ6f3uB9tEOAu97KlyAfpHlfDnVmoRQrMQalKhvLmfE0yP0EMuPhYYGtn7jatuXmdfMfFrLAJ9ugcTi2JMAieJsn/G1UFBLiCyUevpcn4yr/pO7diNqmuw+rGlSHj8NxOxNvaeHUCCik6Sin8Cu3i9P/nrXvMxzGL7SJRCBtqa/f7vrCoeTm75/AkjhPUL05/QvESfuzMRM/VjIYrTmmn3je/ET+2LUhKgjnyNScGm89gope9evHl7kC1LLbb8NU3ImgXmaLmLnLBjZT0T7Ti7DS5m+FTJ9tblI59sfCzjuqN0DAm6DK7exS/wu3RtOjP7EV/98QGCg="