sudo: required
language: generic

services:
    - docker

env:
    - TMDb_KEY=$TMDb_KEY

before_install:
    - docker build -t jchen96/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jchen96/react-test npm run test

after_sucess:
    - docker build -t jchen96/movie-client ./client
    - docker build -t jchen96/movie-nginx ./nginx
    - docker build -t jchen96/movie-server ./server
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - echo "$TMDb_KEY"
    - docker push jchen96/movie-client
    - docker push jchen96/movie-nginx
    - docker push jchen96/movie-server

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'movie-docker'
  env: 'MovieDocker-env-1'
  bucket_name: 'elasticbeanstalk-us-east-2-519589258831'
  bucket_path: 'movie-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY